### PR TITLE
GUI example to perform inventory with sllurp

### PR DESCRIPTION
**Pull request by papapel**
Hello @fviard 

I want to share with you a pyqt based GUI which implements your version of sllurp.
It performs inventory only.

Let me know.

### CODE REVIEW

**Comment by fviard** [comment]
Nice PR.
Someone already did a small GUI for his research, but hasn't shared it yet maybe because not cleaned up.
So, I guess your GUI is a good start at having one.

I will give it a try tomorrow also.
First suggestion that I would have, is maybe to rename the folder from "gui" to "qtgui" or "qt5gui", as it is in examples, it might be nicer if someone wants to add GUIs based on another framework, or looking for examples to use sllurp with qt.

**Comment by fviard** [comment]
I tested it, and even if limited in features, it is a very great work!
It would be great if you continue to improve it.
(Please look at the my branch a little bit later as I will change a very few things)

**Comment by fviard** [comment]
I have pushed the small change to fix the mask issue.

**Comment by fviard** [comment]
Btw, an issue to follow up the dev:
https://github.com/fviard/sllurp/issues/6

**Comment by papapel** [comment]
Thank you for accepting the pull request. 
I glad to know it works.
Good suggestion to rename the example from `gui` to `qt5gui`. You did well.

Here is a list of improvements (which I can do once I will have time):
- memory dump
- read/write a specific word
- pyinstaller command to generate a single-file exe for Linux and Windows

**Pull request merged**
